import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { FaHome } from 'react-icons/fa';
import { HiDotsCircleHorizontal } from 'react-icons/hi';
import { BiReceipt } from 'react-icons/bi';
import { BsFillGearFill } from 'react-icons/bs';
import DataTable from '@/components/home-components/DataTable';


const Home = () => {
  return (
    <div>
      <Head>
        <title>xyz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="flex w-[1920px]">
        {/* side bar */}
        <aside className="sidebar w-[220px] bg-light-dark ">
          {
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].map(i => {
              return (
                <div key={i} className="flex items-center my-5">

                  <div className="h-8 w-8 rounded-full bg-dark mx-5">
                    <Image className='mt-2 mx-auto' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                  </div>

                  <span className="text-white">Cricket</span>
                  <Image className="ml-auto mr-2" src={"/icons/arrow-top.png"} height={18} width={18} alt="" />
                </div>
              )
            })
          }
        </aside>
        {/* right content */}
        <section className="right-content  grow">


          <section>
            <div className="flex">
              <div className=' w-[50%]'>
                <div className='bg-primary text-center p-2 text-white'>
                  <div className="flex items-center justify-center">
                    <div className='bg-[red] h-2 w-2 rounded-full mr-2'>

                    </div>
                    <h2>IN PLAY</h2>
                  </div>
                </div>

                <div className="p-3 grid grid-cols-5">
                  {["01.png", "02.png", "03.png", "04.png", "05.png", "06.png", "07.png", "08.png", "09.png", "10.png"].map(i => (
                    <div key={i} className='relative my-1'>
                      <Image className='' src={`/images/in-play/${i}`} width={150} height={180} alt="" />
                      <h3 className='absolute bottom-2 font-bold left-8 shadow-lg'>Live Cricket</h3>
                    </div>
                  ))}
                </div>

              </div>

              {/* slider start */}

              <div className=' w-[50%]'>
                <div className='bg-light-dark text-center p-2 text-white'>
                  <h2>UPCOMMING SPORTS</h2>
                </div>

                <div className="mt-2 relative">
                  <Image src={"/images/slider.png"} height={379} width={850} alt="slider" />
                  <div className='absolute left-[139px] bottom-[68px] text-white '>
                    <h3 className='text-3xl font-bold'>Next Level Game</h3>
                    <p className='text-base font-semibold mb-1'>Next level game</p>
                    <button className='btn bg-primary px-5 py-1'>Take A Ride</button>

                    <div className='flex gap-3 items-center mt-4'>
                      {
                        [1, 2, 4, 5, 6, 6].map(i => (
                          <div key={i} className="h-1 w-[87px] bg-white"></div>
                        ))
                      }
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </section>

          {/* slider end */}

          <section className='flex ml-4'>

            <div className='w-[1215px]'>
              {/* top nav */}
              <div className="bg-primary w-full flex justify-between items-center px-3 py-1">
                <h2 className='text-2xl text-white font-semibold'>Live Bet</h2>
                <div>
                  {/* <input className='p-1 rounded-sm' type="text" name="" defaultValue={"search..."} id="" /> */}
                  <label for="simple-search" class="sr-only">Search</label>
                  <div class="relative w-full">
                    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                      <svg aria-hidden="true" class="w-5 h-5 text-gray-500 " fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                    </div>
                    <input type="text" id="simple-search" class="bg-gray-50  text-black text-sm rounded-sm  block w-full pl-10 p-2  dark:bg-gray-700 " placeholder="Search..." />
                  </div>
                </div>
              </div>

              {/* bottom nav */}

              <div className='bg-secondary w-full p-2'>
                <nav>
                  <ul className='flex items-center'>
                    <li className='text-white text-2xl mr-2'> <FaHome /> </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Cricket
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      football
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Vollyball
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Tennis
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      BaseBall
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Football
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Ruqby
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Vollyball
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Table Tennis
                    </li>

                    <li className='text-white text-[14px] flex items-center justify-start mr-2'>
                      <div className="h-5 w-5 rounded-full bg-dark mx-3">
                        <Image className=' mx-auto mt-[2px]' src={"/icons/cricket.png"} height={18} width={18} alt="" />
                      </div>
                      Mobile App
                    </li>

                    <li className="text-white ml-auto text-2xl">
                      <HiDotsCircleHorizontal />
                    </li>


                  </ul>
                </nav>

              </div>
              {/* second nav section end here ================================================ */}


              {/* data table start here =================================================== */}

              <DataTable />

            </div>
            <div className='grow bg-light-dark ml-2'>

              <div className="flex">
                <div className="text-white flex items-center justify-center bg-primary  w-1/2 py-1.5 ">
                  <span className="text-xl mr-4"><BiReceipt /></span>
                  <h4 className="text-[22px] font-semibold">Bet Slip</h4>
                </div>
                <div className="text-white flex items-center justify-center bg-secondary  w-1/2 py-1.5 ">
                  <span className="text-xl mr-4" ><BiReceipt /></span>
                  <h4 className="text-[22px] font-semibold">Bet Slip</h4>
                </div>

              </div>


              <div className="flex justify-between items-center py-4 mx-3">
              <h4 className="text-[22px] font-semibold text-white">Your Bets</h4>
              <span className="text-xl text-white bg-secondary p-1 rounded" ><BsFillGearFill /></span>

              </div>
              <div className="bg-light rounded-lg  h-38 ">
                      jfdk
              </div>


            </div>


          </section>

        </section>




      </div>

    </div>
  )
}

export default Home